services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_TRUSTED_CONNECTION: ${DB_TRUSTED_CONNECTION}
      DB_TRUST_SERVER_CERTIFICATE: ${DB_TRUST_SERVER_CERTIFICATE}

