name: CI

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Check backend
        working-directory: backend
        run: python -m py_compile test.py

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build
        
  api-test:
    runs-on: ubuntu-latest
    needs: [backend, docker] # Chờ backend và docker build xong mới chạy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 1. Cài đặt Newman
      - name: Install Newman
        run: npm install -g newman

      # 2. Khởi chạy hệ thống bằng Docker Compose để có Server test
      - name: Start Services with Docker
        run: |
          docker compose up -d --build
          sleep 10 # Chờ 10 giây để DB và Backend khởi động xong hoàn toàn

      # 3. Chạy Newman API Test từ thư mục .postman
      - name: Run Postman Tests with Newman
        run: |
          newman run .postman/*.json

      # 4. Tắt môi trường Docker sau khi test xong
      - name: Stop Services
        if: always()
        run: docker compose down